# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5n7zBRztVtOF8MWNv1JMnQyL5qISd11
"""

import streamlit as st
import sqlite3
from datetime import datetime
import pandas as pd

# ----------------------------
# Database setup
# ----------------------------
conn = sqlite3.connect("vms.db", check_same_thread=False)
c = conn.cursor()

c.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    role TEXT,
    department TEXT,
    status TEXT DEFAULT 'Available'
)
""")

c.execute("""
CREATE TABLE IF NOT EXISTS visitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    purpose TEXT,
    employee_id INTEGER,
    visit_date_time TEXT,
    exit_time TEXT,
    duration TEXT,
    status TEXT DEFAULT 'Pending'
)
""")
conn.commit()

# ----------------------------
# Helper functions
# ----------------------------
def add_employee(name, role, department):
    c.execute("INSERT INTO employees (name, role, department) VALUES (?, ?, ?)", (name, role, department))
    conn.commit()

def edit_employee(emp_id, name, role, department):
    c.execute("UPDATE employees SET name=?, role=?, department=? WHERE id=?", (name, role, department, emp_id))
    conn.commit()

def delete_employee(emp_id):
    c.execute("DELETE FROM employees WHERE id=?", (emp_id,))
    conn.commit()

def add_visitor(name, phone, company, purpose, employee_id, visit_dt):
    c.execute("""INSERT INTO visitors (name, phone, company, purpose, employee_id, visit_date_time, status)
                 VALUES (?, ?, ?, ?, ?, ?, 'Pending')""",
                 (name, phone, company, purpose, employee_id, visit_dt))
    conn.commit()

def approve_visitor(visitor_id):
    c.execute("UPDATE visitors SET status='Approved' WHERE id=?", (visitor_id,))
    conn.commit()

def reject_visitor(visitor_id):
    c.execute("UPDATE visitors SET status='Rejected' WHERE id=?", (visitor_id,))
    conn.commit()

def reschedule_visitor(visitor_id, new_dt):
    c.execute("UPDATE visitors SET visit_date_time=?, status='Pending' WHERE id=?", (new_dt, visitor_id))
    conn.commit()

def mark_exit(visitor_id):
    exit_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.execute("SELECT visit_date_time FROM visitors WHERE id=?", (visitor_id,))
    start_time = c.fetchone()[0]
    if start_time:
        start_dt = datetime.strptime(start_time, "%Y-%m-%d %H:%M:%S")
        exit_dt = datetime.strptime(exit_time, "%Y-%m-%d %H:%M:%S")
        duration = str(exit_dt - start_dt)
    else:
        duration = "Unknown"
    c.execute("UPDATE visitors SET exit_time=?, duration=?, status='Completed' WHERE id=?",
              (exit_time, duration, visitor_id))
    conn.commit()

def get_employees():
    c.execute("SELECT * FROM employees")
    return c.fetchall()

def get_visitors():
    c.execute("SELECT * FROM visitors")
    return c.fetchall()

def get_employee_by_id(emp_id):
    c.execute("SELECT * FROM employees WHERE id=?", (emp_id,))
    return c.fetchone()

# ----------------------------
# Streamlit UI
# ----------------------------
st.set_page_config(page_title="Visitor Management System", layout="wide")
st.title("Visitor Management System")

role_option = st.sidebar.selectbox("Select Role", ["Receptionist", "Employee", "Admin"])

# ----------------------------
# Receptionist
# ----------------------------
if role_option == "Receptionist":
    st.subheader("Receptionist Dashboard")

    # Employee Management Sidebar
    st.sidebar.header("Employee Management")
    employees = get_employees()
    emp_names = [e[1] for e in employees]

    add_emp_name = st.sidebar.text_input("Name")
    add_emp_role = st.sidebar.text_input("Role")
    add_emp_dept = st.sidebar.text_input("Department")
    if st.sidebar.button("Add Employee"):
        if add_emp_name and add_emp_role and add_emp_dept:
            add_employee(add_emp_name, add_emp_role, add_emp_dept)
            st.experimental_rerun()

    st.sidebar.markdown("### Edit/Delete Employee")
    selected_emp = st.sidebar.selectbox("Select Employee", [""] + emp_names)
    if selected_emp:
        emp_data = [e for e in employees if e[1] == selected_emp][0]
        new_name = st.sidebar.text_input("Name", emp_data[1])
        new_role = st.sidebar.text_input("Role", emp_data[2])
        new_dept = st.sidebar.text_input("Department", emp_data[3])
        col1, col2 = st.sidebar.columns(2)
        if col1.button("Update Employee"):
            edit_employee(emp_data[0], new_name, new_role, new_dept)
            st.experimental_rerun()
        if col2.button("Delete Employee"):
            delete_employee(emp_data[0])
            st.experimental_rerun()

    # Visitor Registration
    st.markdown("### Register Visitor")
    visitor_name = st.text_input("Visitor Name")
    visitor_phone = st.text_input("Phone")
    visitor_company = st.text_input("Company")
    visitor_purpose = st.text_input("Purpose")
    available_emps = [e for e in employees if e[4] == "Available"]
    emp_options = {e[1]: e[0] for e in available_emps}
    selected_emp = st.selectbox("Assign Employee (Available Only)", [""] + list(emp_options.keys()))
    visit_dt = st.datetime_input("Visit Date & Time", datetime.now())
    if st.button("Add Visitor"):
        if visitor_name:
            emp_id = emp_options.get(selected_emp, None)
            add_visitor(visitor_name, visitor_phone, visitor_company, visitor_purpose,
                        emp_id, visit_dt.strftime("%Y-%m-%d %H:%M:%S"))
            st.success("Visitor added (Pending Approval)")
            st.experimental_rerun()

    # Visitor Dashboard
    st.markdown("### Visitor Dashboard")
    visitors = get_visitors()
    if visitors:
        visitor_data = []
        for v in visitors:
            emp_name = get_employee_by_id(v[5])[1] if get_employee_by_id(v[5]) else "Not Assigned"
            visitor_data.append([v[0], v[1], v[2], v[3], v[4], emp_name, v[6], v[7], v[8], v[9]])
        df = pd.DataFrame(visitor_data, columns=["ID", "Name", "Phone", "Company", "Purpose",
                                                 "Employee", "Visit Time", "Exit Time", "Duration", "Status"])
        st.dataframe(df)
        # Only allow marking exit for Approved visitors
        for v in visitors:
            if v[9] == "Approved":
                if st.button(f"Mark Exit for {v[1]}", key=f"exit{v[0]}"):
                    mark_exit(v[0])
                    st.experimental_rerun()
    else:
        st.info("No visitors yet.")

# ----------------------------
# Employee
# ----------------------------
elif role_option == "Employee":
    st.subheader("Employee Dashboard")
    emp_name_input = st.text_input("Enter your name")
    employees = get_employees()
    emp_obj = [e for e in employees if e[1].lower() == emp_name_input.lower()]
    if emp_obj:
        emp = emp_obj[0]
        st.write(f"Welcome, {emp[1]} | Status: {emp[4]}")
        new_status = st.selectbox("Update Status", ["Available", "Busy", "Not Free Today"],
                                  index=["Available","Busy","Not Free Today"].index(emp[4]))
        if st.button("Update Status"):
            c.execute("UPDATE employees SET status=? WHERE id=?", (new_status, emp[0]))
            conn.commit()
            st.success("Status Updated!")
            st.experimental_rerun()

        st.markdown("### Pending Visitors")
        c.execute("SELECT * FROM visitors WHERE employee_id=? AND status='Pending'", (emp[0],))
        pending_visitors = c.fetchall()
        if pending_visitors:
            for v in pending_visitors:
                st.write(f"Visitor: {v[1]} | Purpose: {v[4]} | Scheduled: {v[6]}")
                col1, col2, col3 = st.columns(3)
                if col1.button(f"Approve {v[0]}", key=f"approve{v[0]}"):
                    approve_visitor(v[0])
                    st.experimental_rerun()
                if col2.button(f"Reject {v[0]}", key=f"reject{v[0]}"):
                    reject_visitor(v[0])
                    st.experimental_rerun()
                if col3.button(f"Reschedule {v[0]}", key=f"reschedule{v[0]}"):
                    new_dt = st.datetime_input(f"New DateTime for {v[1]}", datetime.now(), key=f"reschedule_dt{v[0]}")
                    reschedule_visitor(v[0], new_dt.strftime("%Y-%m-%d %H:%M:%S"))
                    st.experimental_rerun()
        else:
            st.info("No pending visitors.")

# ----------------------------
# Admin
# ----------------------------
elif role_option == "Admin":
    st.subheader("Admin Dashboard")
    visitors = get_visitors()
    employees = get_employees()
    emp_dict = {e[0]: e[1] for e in employees}
    if visitors:
        visitor_data = []
        for v in visitors:
            emp_name = emp_dict.get(v[5], "Not Assigned")
            visitor_data.append([v[0], v[1], v[2], v[3], v[4], emp_name, v[6], v[7], v[8], v[9]])
        df = pd.DataFrame(visitor_data, columns=["ID", "Name", "Phone", "Company", "Purpose",
                                                 "Employee", "Visit Time", "Exit Time", "Duration", "Status"])
        st.dataframe(df)
        csv = df.to_csv(index=False).encode('utf-8')
        st.download_button("Download CSV", csv, "visitors.csv", "text/csv")
    else:
        st.info("No visitors yet.")