# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5n7zBRztVtOF8MWNv1JMnQyL5qISd11
"""

import streamlit as st
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

# --- Database Setup ---
conn = sqlite3.connect("vms.db", check_same_thread=False)
c = conn.cursor()

# Employees table
c.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    role TEXT,
    department TEXT,
    status TEXT DEFAULT 'Available'
)
""")

# Visitors table
c.execute("""
CREATE TABLE IF NOT EXISTS visitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    purpose TEXT,
    employee_id INTEGER,
    employee_name TEXT,
    visit_date_time TEXT,
    status TEXT DEFAULT 'Pending',
    exit_time TEXT,
    duration TEXT,
    FOREIGN KEY(employee_id) REFERENCES employees(id)
)
""")
conn.commit()

# --- Helper Functions ---
def get_employees_df():
    return pd.read_sql("SELECT * FROM employees", conn)

def get_visitors_df():
    return pd.read_sql("SELECT * FROM visitors", conn)

def add_employee(name, role, department):
    c.execute("INSERT INTO employees (name, role, department) VALUES (?, ?, ?)", (name, role, department))
    conn.commit()

def update_employee(emp_id, name, role, department, status):
    c.execute("UPDATE employees SET name=?, role=?, department=?, status=? WHERE id=?", (name, role, department, status, emp_id))
    conn.commit()

def delete_employee(emp_id):
    c.execute("DELETE FROM employees WHERE id=?", (emp_id,))
    conn.commit()

def add_visitor(name, phone, company, purpose, emp_id, emp_name, visit_dt):
    c.execute("INSERT INTO visitors (name, phone, company, purpose, employee_id, employee_name, visit_date_time) VALUES (?, ?, ?, ?, ?, ?, ?)",
              (name, phone, company, purpose, emp_id, emp_name, visit_dt))
    conn.commit()

def update_visitor_status(visitor_id, status, new_time=None):
    if new_time:
        c.execute("UPDATE visitors SET status=?, visit_date_time=? WHERE id=?", (status, new_time, visitor_id))
    else:
        c.execute("UPDATE visitors SET status=? WHERE id=?", (status, visitor_id))
    conn.commit()

def mark_exit(visitor_id):
    exit_time = datetime.now()
    c.execute("SELECT visit_date_time FROM visitors WHERE id=?", (visitor_id,))
    visit_time = datetime.strptime(c.fetchone()[0], "%Y-%m-%d %H:%M:%S")
    duration = exit_time - visit_time
    c.execute("UPDATE visitors SET exit_time=?, duration=?, status='Completed' WHERE id=?", (exit_time.strftime("%Y-%m-%d %H:%M:%S"), str(duration), visitor_id))
    conn.commit()

# --- Streamlit UI ---
st.title("Visitor Management System")

# Role Selection
role = st.sidebar.selectbox("Login as", ["Receptionist", "Employee", "Admin"])

# Load Data
employees_df = get_employees_df()
visitors_df = get_visitors_df()

# --- Receptionist Panel ---
if role == "Receptionist":
    st.header("Receptionist Dashboard")

    # Employee Management Sidebar
    st.sidebar.subheader("Employee Management")
    with st.sidebar.expander("Add Employee"):
        e_name = st.text_input("Name", key="add_name")
        e_role = st.text_input("Role", key="add_role")
        e_dept = st.text_input("Department", key="add_dept")
        if st.button("Add Employee"):
            if e_name.strip():
                add_employee(e_name, e_role, e_dept)
                st.success("Employee Added!")
                st.experimental_rerun()

    st.sidebar.subheader("Edit/Delete Employee")
    for _, row in employees_df.iterrows():
        with st.sidebar.expander(f"{row['name']}"):
            new_name = st.text_input("Name", row['name'], key=f"name_{row['id']}")
            new_role = st.text_input("Role", row['role'], key=f"role_{row['id']}")
            new_dept = st.text_input("Dept", row['department'], key=f"dept_{row['id']}")
            new_status = st.selectbox("Status", ["Available", "In Meeting", "Not Free Today"], index=["Available","In Meeting","Not Free Today"].index(row['status']), key=f"status_{row['id']}")
            if st.button("Update", key=f"update_{row['id']}"):
                update_employee(row['id'], new_name, new_role, new_dept, new_status)
                st.success("Employee Updated!")
                st.experimental_rerun()
            if st.button("Delete", key=f"delete_{row['id']}"):
                delete_employee(row['id'])
                st.success("Employee Deleted!")
                st.experimental_rerun()

    st.subheader("Register Visitor")
    pending_emps = employees_df[employees_df['status'] == 'Available']
    if pending_emps.empty:
        st.warning("No Available Employees")
    else:
        v_name = st.text_input("Visitor Name")
        v_phone = st.text_input("Phone")
        v_company = st.text_input("Company")
        v_purpose = st.text_input("Purpose")
        selected_emp = st.selectbox("Assign Employee", pending_emps['name'])
        visit_dt = st.datetime_input("Visit Date & Time", datetime.now())
        if st.button("Add Visitor"):
            emp_row = pending_emps[pending_emps['name'] == selected_emp].iloc[0]
            add_visitor(v_name, v_phone, v_company, v_purpose, emp_row['id'], emp_row['name'], visit_dt.strftime("%Y-%m-%d %H:%M:%S"))
            st.success("Visitor Added (Pending Approval)")
            st.experimental_rerun()

    st.subheader("Visitor Dashboard")
    if not visitors_df.empty:
        visitors_df['employee_name'] = visitors_df['employee_name'].fillna('')
        tab1, tab2, tab3 = st.tabs(["Pending", "Approved", "Completed"])

        with tab1:
            pending_vis = visitors_df[visitors_df['status'].isin(['Pending', 'Rescheduled'])]
            st.dataframe(pending_vis[['id','name','phone','company','purpose','employee_name','visit_date_time','status']])

        with tab2:
            approved_vis = visitors_df[visitors_df['status'] == 'Approved']
            st.dataframe(approved_vis[['id','name','phone','company','purpose','employee_name','visit_date_time','status']])
            for _, row in approved_vis.iterrows():
                if st.button(f"Mark Exit {row['id']}", key=f"exit_{row['id']}"):
                    mark_exit(row['id'])
                    st.success("Exit Marked & Duration Calculated")
                    st.experimental_rerun()

        with tab3:
            completed_vis = visitors_df[visitors_df['status'] == 'Completed']
            st.dataframe(completed_vis[['id','name','phone','company','purpose','employee_name','visit_date_time','exit_time','duration','status']])
    else:
        st.info("No visitors yet")

# --- Employee Panel ---
elif role == "Employee":
    st.header("Employee Dashboard")
    emp_name = st.text_input("Enter Your Name")
    if emp_name.strip():
        emp_row = employees_df[employees_df['name'] == emp_name]
        if not emp_row.empty:
            emp_id = emp_row.iloc[0]['id']
            # Update status
            new_status = st.selectbox("Update Status", ["Available","In Meeting","Not Free Today"], index=["Available","In Meeting","Not Free Today"].index(emp_row.iloc[0]['status']))
            if st.button("Update Status"):
                update_employee(emp_id, emp_name, emp_row.iloc[0]['role'], emp_row.iloc[0]['department'], new_status)
                st.success("Status Updated")
                st.experimental_rerun()

            st.subheader("Pending Visitor Requests")
            pending_vis = visitors_df[(visitors_df['employee_id']==emp_id) & (visitors_df['status'].isin(['Pending','Rescheduled']))]
            for _, row in pending_vis.iterrows():
                st.write(f"Visitor: {row['name']} | Time: {row['visit_date_time']} | Purpose: {row['purpose']}")
                col1, col2, col3 = st.columns(3)
                with col1:
                    if st.button(f"Approve {row['id']}", key=f"approve_{row['id']}"):
                        update_visitor_status(row['id'], "Approved")
                        st.success("Visitor Approved")
                        st.experimental_rerun()
                with col2:
                    if st.button(f"Reject {row['id']}", key=f"reject_{row['id']}"):
                        update_visitor_status(row['id'], "Rejected")
                        st.success("Visitor Rejected")
                        st.experimental_rerun()
                with col3:
                    resched_dt = st.date_input("Reschedule Date", datetime.strptime(row['visit_date_time'], "%Y-%m-%d %H:%M:%S"))
                    resched_tm = st.time_input("Reschedule Time", datetime.strptime(row['visit_date_time'], "%Y-%m-%d %H:%M:%S").time())
                    if st.button(f"Reschedule {row['id']}", key=f"resched_{row['id']}"):
                        new_dt = datetime.combine(resched_dt, resched_tm)
                        update_visitor_status(row['id'], "Rescheduled", new_dt.strftime("%Y-%m-%d %H:%M:%S"))
                        st.success("Visitor Rescheduled")
                        st.experimental_rerun()
        else:
            st.warning("Employee not found")

# --- Admin Panel ---
elif role == "Admin":
    st.header("Admin Dashboard")
    st.subheader("All Visitor Data")
    st.dataframe(visitors_df)
    st.download_button("Download CSV", visitors_df.to_csv(index=False), "visitor_data.csv")