# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5n7zBRztVtOF8MWNv1JMnQyL5qISd11
"""

import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime

st.set_page_config(page_title="Visitor Management System", layout="wide")

# Connect to SQLite
conn = sqlite3.connect("vms.db", check_same_thread=False)
c = conn.cursor()

# Create tables
c.execute('''
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    department TEXT,
    role TEXT,
    status TEXT DEFAULT 'Available'
)
''')

c.execute('''
CREATE TABLE IF NOT EXISTS visitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    phone TEXT,
    company TEXT,
    purpose TEXT,
    employee_id INTEGER,
    visit_date_time TEXT,
    exit_time TEXT,
    duration TEXT,
    status TEXT DEFAULT 'Pending',
    FOREIGN KEY(employee_id) REFERENCES employees(id)
)
''')
conn.commit()

# Utility Functions
def get_employees():
    df = pd.read_sql("SELECT * FROM employees", conn)
    return df

def get_visitors():
    df = pd.read_sql("SELECT * FROM visitors", conn)
    # Merge employee names for display
    df = df.merge(get_employees()[['id','name']], left_on='employee_id', right_on='id', how='left', suffixes=('','_emp'))
    df.rename(columns={'name_emp':'employee_name'}, inplace=True)
    df.drop(columns=['id_emp'], inplace=True, errors='ignore')
    return df

def add_employee(name, department, role):
    c.execute("INSERT INTO employees (name, department, role) VALUES (?, ?, ?)", (name, department, role))
    conn.commit()

def edit_employee(emp_id, name, department, role, status):
    c.execute("UPDATE employees SET name=?, department=?, role=?, status=? WHERE id=?", (name, department, role, status, emp_id))
    conn.commit()

def delete_employee(emp_id):
    c.execute("DELETE FROM employees WHERE id=?", (emp_id,))
    conn.commit()

def add_visitor(name, phone, company, purpose, employee_id, visit_dt):
    c.execute('''INSERT INTO visitors
                 (name, phone, company, purpose, employee_id, visit_date_time, status)
                 VALUES (?, ?, ?, ?, ?, ?, ?)''',
              (name, phone, company, purpose, employee_id, visit_dt, "Pending"))
    conn.commit()

def update_visitor_status(visitor_id, status, new_dt=None):
    if new_dt:
        c.execute("UPDATE visitors SET status=?, visit_date_time=? WHERE id=?", (status, new_dt, visitor_id))
    else:
        c.execute("UPDATE visitors SET status=? WHERE id=?", (status, visitor_id))
    conn.commit()

def mark_exit(visitor_id):
    exit_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.execute("SELECT visit_date_time FROM visitors WHERE id=?", (visitor_id,))
    visit_time_str = c.fetchone()[0]
    visit_time = datetime.strptime(visit_time_str, "%Y-%m-%d %H:%M:%S")
    duration = datetime.strptime(exit_time, "%Y-%m-%d %H:%M:%S") - visit_time
    c.execute("UPDATE visitors SET exit_time=?, duration=?, status='Completed' WHERE id=?", (exit_time, str(duration), visitor_id))
    conn.commit()

# --- Sidebar ---
st.sidebar.title("Visitor Management System")
role = st.sidebar.selectbox("Select Role", ["Receptionist","Employee","Admin"])

# --- Receptionist Panel ---
if role=="Receptionist":
    st.title("Receptionist Dashboard")

    # Employee Management Sidebar
    st.sidebar.subheader("Manage Employees")
    employees_df = get_employees()

    with st.sidebar.expander("Add Employee"):
        e_name = st.text_input("Name")
        e_department = st.text_input("Department")
        e_role = st.text_input("Role")
        if st.button("Add Employee"):
            if e_name and e_role:
                add_employee(e_name, e_department, e_role)
                st.success("Employee Added")

    if not employees_df.empty:
        for idx,row in employees_df.iterrows():
            st.sidebar.write(f"ID:{row['id']} - {row['name']}")
            new_name = st.sidebar.text_input("Name", row['name'], key=f"name{row['id']}")
            new_dept = st.sidebar.text_input("Dept", row['department'], key=f"dept{row['id']}")
            new_role = st.sidebar.text_input("Role", row['role'], key=f"role{row['id']}")
            new_status = st.sidebar.selectbox("Status", ["Available","Already in a Meeting","Not Free Today"], index=["Available","Already in a Meeting","Not Free Today"].index(row['status']), key=f"status{row['id']}")
            col1,col2 = st.sidebar.columns(2)
            if col1.button("Save", key=f"save{row['id']}"):
                edit_employee(row['id'], new_name, new_dept, new_role, new_status)
                st.success("Updated")
            if col2.button("Delete", key=f"del{row['id']}"):
                delete_employee(row['id'])
                st.success("Deleted")

    st.subheader("Register Visitor")
    visitors_df = get_visitors()
    if employees_df.empty:
        st.warning("No Employees Available")
    else:
        v_name = st.text_input("Visitor Name")
        v_phone = st.text_input("Phone")
        v_company = st.text_input("Company")
        v_purpose = st.text_input("Purpose")
        selected_emp = st.selectbox("Select Employee", employees_df['name'])
        emp_row = employees_df[employees_df['name']==selected_emp].iloc[0]
        visit_datetime = st.datetime_input("Visit Date & Time", datetime.now())
        if st.button("Send Visitor Request"):
            if emp_row['status']!="Available":
                st.warning(f"Employee is {emp_row['status']}. Cannot send request.")
            else:
                add_visitor(v_name,v_phone,v_company,v_purpose,emp_row['id'], visit_datetime.strftime("%Y-%m-%d %H:%M:%S"))
                st.success("Visitor Added (Pending Approval)")

    st.subheader("Visitors Dashboard")
    visitors_df = get_visitors()
    if not visitors_df.empty:
        st.dataframe(visitors_df[['id','name','phone','company','purpose','employee_name','visit_date_time','exit_time','duration','status']])
        for idx,row in visitors_df.iterrows():
            if row['status']=="Completed" and pd.isna(row['exit_time']):
                if st.button(f"Mark Exit for {row['name']}", key=f"exit{row['id']}"):
                    mark_exit(row['id'])
                    st.success("Exit Marked")

# --- Employee Panel ---
elif role=="Employee":
    st.title("Employee Dashboard")
    employees_df = get_employees()
    selected_name = st.text_input("Enter Your Name")
    if selected_name:
        emp = employees_df[employees_df['name']==selected_name]
        if not emp.empty:
            emp_id = emp.iloc[0]['id']
            st.write(f"Hello {selected_name}")
            visitors_df = get_visitors()
            emp_visitors = visitors_df[(visitors_df['employee_id']==emp_id) & (visitors_df['status']=="Pending")]
            if emp_visitors.empty:
                st.info("No Pending Visitor Requests")
            else:
                st.subheader("Pending Visitor Requests")
                for idx,row in emp_visitors.iterrows():
                    st.write(f"{row['name']} - {row['visit_date_time']}")
                    col1,col2,col3 = st.columns(3)
                    if col1.button("Approve", key=f"ap{row['id']}"):
                        update_visitor_status(row['id'],"Approved")
                        st.success("Visitor Approved")
                    if col2.button("Reject", key=f"rj{row['id']}"):
                        update_visitor_status(row['id'],"Rejected")
                        st.success("Visitor Rejected")
                    if col3.button("Reschedule", key=f"rs{row['id']}"):
                        new_dt = st.datetime_input("New Date & Time", datetime.now(), key=f"resch{row['id']}")
                        update_visitor_status(row['id'],"Pending", new_dt.strftime("%Y-%m-%d %H:%M:%S"))
                        st.success("Visitor Rescheduled")
            # Employee can update status
            new_status = st.selectbox("Update Availability Status", ["Available","Already in a Meeting","Not Free Today"], index=["Available","Already in a Meeting","Not Free Today"].index(emp.iloc[0]['status']))
            if st.button("Save Status"):
                edit_employee(emp_id, emp.iloc[0]['name'], emp.iloc[0]['department'], emp.iloc[0]['role'], new_status)
                st.success("Status Updated")
        else:
            st.warning("Name not found.")

# --- Admin Panel ---
elif role=="Admin":
    st.title("Admin Dashboard")
    visitors_df = get_visitors()
    st.subheader("All Visitors")
    filter_emp = st.selectbox("Filter by Employee", ["All"] + list(get_employees()['name']))
    filter_date = st.date_input("Filter by Date")
    filtered_visitors = visitors_df.copy()
    if filter_emp!="All":
        filtered_visitors = filtered_visitors[filtered_visitors['employee_name']==filter_emp]
    filtered_visitors = filtered_visitors[filtered_visitors['visit_date_time'].str.startswith(filter_date.strftime("%Y-%m-%d"))]
    st.dataframe(filtered_visitors[['id','name','phone','company','purpose','employee_name','visit_date_time','exit_time','duration','status']])
    st.download_button("Download CSV", filtered_visitors.to_csv(index=False), "visitors.csv", "text/csv")